name: Unanet Import Integration

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 9 * * *'
  #   - cron: '0 12 * * *'
  #   - cron: '0 15 * * *'

permissions:
  contents: read

jobs:
  unanet-integration:
    name: Run Unanet Integration
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install paramiko
          python -m pip install pandas


      - name: Update IMU Config
        run: |
          echo unanet.url=${{ secrets.UNANET_URL }} > unanet_imu/imu_config.properties
          echo username=${{ secrets.UNANET_USERNAME }} >> unanet_imu/imu_config.properties
          echo password=${{ secrets.UNANET_PASSWORD }} >> unanet_imu/imu_config.properties
          echo email.host=${{ secrets.EMAIL_HOST }} >> unanet_imu/imu_config.properties
          echo email.port=${{ secrets.EMAIL_PORT }} >> unanet_imu/imu_config.properties
          echo email.from=${{ secrets.EMAIL_FROM }} >> unanet_imu/imu_config.properties
          echo email.to=${{ secrets.EMAIL_TO }} >> unanet_imu/imu_config.properties
          echo email.ssl=false >> unanet_imu/imu_config.properties
          echo email.enableStartTLS=true >> unanet_imu/imu_config.properties
          echo positive.reporting=true >> unanet_imu/imu_config.properties
          echo email.user=${{ secrets.EMAIL_USER }} >> unanet_imu/imu_config.properties
          echo email.password=${{ secrets.EMAIL_PASSWORD }} >> unanet_imu/imu_config.properties
          echo run.imports=person >> unanet_imu/imu_config.properties
          echo person.input.file=import.csv >> unanet_imu/imu_config.properties
          echo person.log.file=import.log >> unanet_imu/imu_config.properties
          echo person.import.template=person >> unanet_imu/imu_config.properties
          echo person.skip-file-check-warning=true >> unanet_imu/imu_config.properties
          echo person.args= >> unanet_imu/imu_config.properties
          echo purge.days=0 >> unanet_imu/imu_config.properties

      - name: Run IMU Import
        run: |
          cd unanet_imu
          ./unanet_imu.bat
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_RSA_PRIVATE_KEY: ${{ secrets.SFTP_RSA_PRIVATE_KEY }}
        continue-on-error: true


